server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.227.111 #Redis服务器地址
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
    password: 123456
